### ISSUE TITLE
Test suite fails (with Math::BigInt::Lite?)

### ISSUE THREAD

**Issue by eserte** [sysread/TOML-Tiny#1]
The test suite fails on some of my smokers, see http://matrix.cpantesters.org/?dist=TOML-Tiny%200.02
This seems to happen if Math::BigInt::Lite is installed.

**Comment by sysread** [comment]
This is caused by TOML::Tiny using the `bignum` pragma to automatically upgrade numbers parsed out of TOML source, which may be larger than perl supports by default. I have removed the automatic upgrade (it can still be achieved with `inflate_integer` and `inflate_float`, which I've added to the unit tests). I'm testing v0.3 to fix this.

**Comment by sysread** [comment]
`v0.3` has been tagged and pushed to CPAN.
